site_name: Docs
theme:
  name: material
  language: es
  favicon: assets/logo-alberties.png
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: light blue  # Cambiado a azul claro
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - header.autohide
    - navigation.indexes

plugins:
  - search:
      lang: es
  - with-pdf:
      author: Manuel Jesús Rivas Sández
      copyright: CC BY-SA 4.0
      cover: true
      cover_title: TITLE TEXT
      cover_subtitle: SUBTITLE TEXT
      toc_title: Tabla de contenidos

nav:
  - Home: index.md

copyright:  Manuel Jesús Rivas Sández

